"""G28A staged revoked-evidence paths, registered in results/discovery.

Runs all final conditions in one model load. The existing ConfB data are read
without filtering or alteration. Initial assistant answers are actually
generated by the same model and inserted into RJ/IJ conversation histories.
"""

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from run_model import digit_expectation  # exact frozen G24A readout
from schema import ANSWER_CUE, SYSTEM


QUESTION = "Considering everything above, rate the likelihood that the claim is true."
SCALE = "Use a scale from 0 to 9, where 0 means certainly false and 9 means certainly true."
FORMAT = "Think in at most two short sentences. Then write a final line of exactly this form:\nANSWER: <your answer>"
UPDATE = ("UPDATE\nEvidence E1 has been withdrawn. It is not admissible and must have zero "
          "influence on your final judgment. Any previous judgment must also "
          "have no influence. Evidence E2 below is the only admissible "
          "additional evidence.")


def sha(s):
    return hashlib.sha256(s.encode("utf-8")).hexdigest()


def task_text():
    return "TASK\n" + QUESTION + "\n" + SCALE + "\n" + FORMAT


def first_judged(claim, evidence):
    return ("CLAIM\n" + claim + "\n\nEVIDENCE E1\n" + evidence +
            "\n\n" + task_text())


def first_read(claim, evidence):
    return ("CLAIM\n" + claim + "\n\nEVIDENCE E1\n" + evidence +
            "\n\nPlease read this information. I will ask for a judgment in the next turn.")


def second(evidence):
    return UPDATE + "\n\nEVIDENCE E2\n" + evidence + "\n\n" + task_text()


def direct(claim, evidence):
    return "CLAIM\n" + claim + "\n\nEVIDENCE E2\n" + evidence + "\n\n" + task_text()


def load_data(path):
    pairs = [json.loads(line) for line in Path(path).read_text().splitlines() if line]
    assert len(pairs) == 200 and len({p["cfb_id"] for p in pairs}) == 200
    controls = {}
    for line in (ROOT / "data/items/g24a_confb_v1.jsonl").read_text().splitlines():
        if line:
            row = json.loads(line)
            if row["meta"]["arm"] == "control":
                controls[row["meta"]["cfb_id"]] = row["critical_evidence"]
    assert set(controls) == {p["cfb_id"] for p in pairs}
    return pairs, controls


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True)
    ap.add_argument("--tag", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--items", default=str(ROOT / "data/items/g24a_confb_selected_v1.jsonl"))
    ap.add_argument("--limit", type=int, default=200, help="first seed-order n, smoke only when n<200")
    ap.add_argument("--gpu-frac", type=float, default=0.85)
    args = ap.parse_args()
    assert 1 <= args.limit <= 200
    pairs, controls = load_data(args.items)
    pairs = pairs[: args.limit]

    from transformers import AutoTokenizer
    from vllm import LLM, SamplingParams

    tok = AutoTokenizer.from_pretrained(args.model)

    def chat_ids(messages):
        full = [{"role": "system", "content": SYSTEM}] + messages
        kw = dict(tokenize=True, add_generation_prompt=True)
        try:
            enc = tok.apply_chat_template(full, enable_thinking=False, **kw)
        except TypeError:
            enc = tok.apply_chat_template(full, **kw)
        ids = enc["input_ids"] if hasattr(enc, "keys") else enc
        return list(ids[0]) if ids and isinstance(ids[0], (list, tuple)) else list(ids)

    def raw_ids(s):
        return tok(s, add_special_tokens=False)["input_ids"]

    llm = LLM(model=args.model, tensor_parallel_size=1,
              gpu_memory_utilization=args.gpu_frac, max_model_len=4096,
              dtype="bfloat16", max_logprobs=40, disable_log_stats=True,
              enforce_eager=True)

    def score(rows):
        """Mutate row dictionaries with the frozen two-stage reasoned readout."""
        for r in rows:
            r["ids"] = chat_ids(r["messages"])
            r["n_prompt_tokens"] = len(r["ids"])
            r["prompt_sha256"] = sha(json.dumps(r["messages"], ensure_ascii=False, sort_keys=True))
        prompts = [{"prompt_token_ids": r["ids"]} for r in rows]
        out1 = llm.generate(prompts, SamplingParams(temperature=0.0, max_tokens=110,
                                                    stop=[ANSWER_CUE]), use_tqdm=False)
        for r, o in zip(rows, out1):
            r["reasoning"] = o.outputs[0].text
            r["reason_truncated"] = o.outputs[0].finish_reason != "stop"
            r["cue"] = r["reasoning"].rstrip() + "\n" + ANSWER_CUE + " "
            r["ids2"] = r["ids"] + raw_ids(r["cue"])
        out2 = llm.generate([{"prompt_token_ids": r["ids2"]} for r in rows],
                            SamplingParams(temperature=0.0, max_tokens=1, logprobs=40),
                            use_tqdm=False)
        for r, o in zip(rows, out2):
            r["raw"] = o.outputs[0].text
            r["value"], r["mass"] = digit_expectation(o)
            r["assistant_text"] = r["cue"] + r["raw"].strip()
            del r["ids"], r["ids2"], r["cue"]
        return rows

    initial = []
    for p in pairs:
        pid, claim = p["cfb_id"], p["claim"]
        for role, evidence in (("support", p["evidence_s"]),
                               ("refute", p["evidence_r"]),
                               ("irrelevant", controls[pid])):
            initial.append({"cfb_id": pid, "stage": "initial", "role": role,
                            "messages": [{"role": "user", "content": first_judged(claim, evidence)}]})
    score(initial)
    init_by = {(r["cfb_id"], r["role"]): r for r in initial}
    assert len(init_by) == 3 * len(pairs)

    final = []
    for p in pairs:
        pid, claim = p["cfb_id"], p["claim"]
        for final_role, e2, old_role, e1 in (("support", p["evidence_s"], "refute", p["evidence_r"]),
                                              ("refute", p["evidence_r"], "support", p["evidence_s"])):
            for cond in ("D", "RJ", "IJ", "RR"):
                if cond == "D":
                    messages = [{"role": "user", "content": direct(claim, e2)}]
                elif cond == "RR":
                    messages = [{"role": "user", "content": first_read(claim, e1)},
                                {"role": "assistant", "content": "Understood."},
                                {"role": "user", "content": second(e2)}]
                else:
                    init_role = old_role if cond == "RJ" else "irrelevant"
                    first = init_by[(pid, init_role)]
                    messages = first["messages"] + [
                        {"role": "assistant", "content": first["assistant_text"]},
                        {"role": "user", "content": second(e2)}]
                final.append({"cfb_id": pid, "stage": "final", "final_role": final_role,
                              "old_role": old_role, "condition": cond, "messages": messages})
    score(final)
    assert len(initial) == 3 * len(pairs) and len(final) == 8 * len(pairs)

    output = Path(args.out)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w") as stream:
        for row in initial + final:
            row["model_tag"] = args.tag
            stream.write(json.dumps(row, ensure_ascii=False) + "\n")
    print(f"wrote {len(initial)} initial and {len(final)} final rows -> {output}")
    print("unparsed", sum(r["value"] is None for r in initial + final),
          "digit-mass<0.5", sum(r["mass"] < 0.5 for r in initial + final),
          "rationale caps", sum(r["reason_truncated"] for r in initial + final))


if __name__ == "__main__":
    main()
